[app_name_here]
    code_url = "INSERT_GIT_REPO_SSH_URL_HERE"
    code_commit_hash = "INSERT_COMMIT_HASH_HERE"
    code_local_path = "Ex: /mnt/abc/def"

    # # Reference:
    # [APP_NAME_HERE]
    #     code_url = "INSERT_GIT_REPO_SSH_URL_HERE"
    #     code_commit_hash = "INSERT_HASH_HERE"
    #     code_local_path = "Ex: /mnt/abc/def, should be absolute"
    #     config_src_path_rel_in_this_repo = "OPTIONAL, Ex: infra_name/config.toml, should be relative to this repo's root"
    #     config_dst_path_abs = "OPTIONAL, Ex: /mnt/abc/def/config.toml, should be absolute path"
    #     pre_updation_command = "OPTIONAL, Ex: git stash"
    #     post_updation_command = "OPTIONAL, Ex: docker restart xyz; git stash pop"
