[app_name_here]
    config_relative_path_in_this_folder = "UPDATE HERE"
    code_url = "INSERT_GIT_REPO_SSH_URL_HERE"
    code_hash = "INSERT_HASH_HERE"
    code_local_path = "/mnt/abc/def"
    config_relative_path_in_code = "UPDATE HERE"

    # # Reference:
    # [APP_NAME_HERE]
    #     config_relative_path_in_this_folder = "INSERT_CONFIG_FILE_RELATIVE_PATH_HERE"
    #     code_url = "INSERT_GIT_REPO_SSH_URL_HERE"
    #     code_hash = "INSERT_HASH_HERE"
    #     code_local_path = "/mnt/abc/def"
    #     post_updation_command = "INSERT_COMMAND_HERE"
