infra_name = "xyz"

[applications]
    [applications.APP1_NAME_HERE]
        config_url = "git@github.com:username/repo1_config.git"
    [applications.app2]
        config_url = "git@github.com:username/repo2_config.git"


        # To add: Feedback/Observability Endpoint - Different branch?
        # To add: Healthcheck Endpoint
        # To add: Deployment Strategy
