infra_name = "xyz"

[applications]
    [applications.APP1_NAME_HERE]
        config_url = "git@github.com:username/repo1_config.git"


        ## REFERENCE STRUCTURE:
        # [applications.INSERT_APP_NAME_HERE]
        #     config_url = "INSERT_GIT_SSH_URL_HERE"
        #     interval = "INSERT INT OF INTERVAL IN SECS, OPTIONAL ARG"


        # To add: Feedback/Observability Endpoint - Different branch?
        # To add: Healthcheck Endpoint
        # To add: Deployment Strategy
